#!/bin/bash -e

happyscheduler_executable="./happyscheduler"
settings_file="config/prod-settings.yml"

if [ -x "$happyscheduler_executable" ]; then

    # note to myself about the 'echo $!'
    # $!  Process ID of the last (righ-most for pipelines) command in the most 
    #	  recently job put into the background (note that it's not 
    #	  necessarily the same as the job's process group ID when job control is enabled)

    pid=$($happyscheduler_executable $settings_file > $happyscheduler_executable.log 2>&1 & echo $!)
    echo "$pid" > $happyscheduler_executable.pid
else
    echo "Executable not found: '${happyscheduler_executable}'"
fi
