Donate: Donate
Loading: Loading...
Welcome: Welcome to Happy Scheduler!
Subtitle: Procrastinate sadness, maximize happyness!
WorkExpands: Work expands so as to fill the time available for its completion.
LastMinute: If you wait until the last minute, it only takes a minute to do.
ShortDescription: A todo list to minimize the time you spend on boring tasks

DescriptionP1: Organize yourself and get through your work. When you leave only the time you need for sad tasks and starts happy tasks as soon as possible, you spend less time on sad tasks, maximizing the time available for happy taks.  Thus, maximizing happyness!

DescriptionP2: Happy Scheduler is a WebApp that allows you manage your ToDo list, that suggest you a starting date for your tasks. Use it to add tasks to your list, to show and to remove tasks from that list. You can classify if it’s a happy or sad task. Then it schedules the tasks for you. Automagically!

LoginInvitation: Login with your google account and start using Happy Scheduler now!
Heuristics: Heuristics
HappyTask: Happy Task
SadTask: Sad Task
HappyTaskDescription: Puts the starting date for sooner as possible;
SadTaskDescription: Procastinates as much as possible.
SourceCode: Source code
HelpUs: Help Us

Support: You can support the project by sharing about HappyScheduler in your social networks, using the webApp and sending sugestions, and by donations for the HappyScheduler can be more and more perfect, and we can pay our bills.

Contribute: Contribute with any value and help us to organize your life.
FeaturesAndBugs: New features and bugs
ToggleNav: Toggle navigation
Home: Home
MyTasks: My Tasks
Login: Login
Logout: Logout
