Lang: pt
Donate: Doações
Loading: Carregando...
Welcome: Bem vindo ao Happy Scheduler!
Subtitle: Procrastine a tristeza, maximize a felicidade!
WorkExpands: O trabalho expande para ocupar o tempo disponível.
LastMinute: Se você esperar até o último mínuto, só vai levar um minuto para fazer.
ShortDescription: Uma lista de tarefas para minimizar o tempo gasto com coisas chatas

DescriptionP1: Se organize e se livre do trabalho. Quando você deixa disponível somente o tempo necessário para realizar as tarefas tristes e inicia as tarefas felizes o quanto antes, você gasta menos tempo com tarefas tristes, maximizando o tempo disponível para tarefas felizes (ou só não fazer nada!).  Portanto, maximizando a felicidade!

DescriptionP2: Happy Scheduler é um WebApp que te permite criar uma lista de tarefas e sugere uma data para iniciar cada uma dessas tarefas. Você classifica se as tarefas são felizes ou tristes. Então ele agenda as tarefas para você. Automagicamente!

LoginInvitation: Faça login com a sua conta do Google e comece a usar o Happy Scheduler agora!
Heuristics: Heurística
HappyTask: Tarefa Feliz
SadTask: Tarefa Triste
HappyTaskDescription: Põe a data de início para o quanto antes;
SadTaskDescription: Procrastina o máximo possível.
SourceCode: Código fonte
HelpUs: Nos Ajude

Support: Você pode apoiar o projeto compartilhando sobre o HappyScheduler nas redes sociais, usando o WebApp e nos mandando sugestões, e nos fazendo uma doação pra nos ajudar a pagar os boletos enquanto trabalhamos neste software ;)

Contribute: Contribua com qualquer valor e nos ajude a te ajudar a organizar a tua vida para seres mais feliz.
FeaturesAndBugs: Pedidos de novas funcionalidades e correção de bugs
ToggleNav: Alternar navegação
Home: Início
MyTasks: Minhas Tarefas
Login: Entrar
Logout: Sair
